name: water_crawler
channels:
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk=2.38.0
  - atk-1.0=2.38.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - dbus=1.16.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - et-xmlfile==2.0.0
      - geographiclib==2.1
      - geopy==2.4.1
      - greenlet==3.3.1
      - idna==3.11
      - numpy==2.4.2
      - openpyxl==3.1.5
      - pandas==3.0.0
      - playwright==1.58.0
      - pyee==13.0.0
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - six==1.17.0
      - typing-extensions==4.15.0
      - urllib3==2.6.3
